from fastapi import FastAPI, HTTPException, Depends
from fastapi.responses import FileResponse
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel
from datetime import date, datetime, timedelta, timezone
import sqlite3
import re
import csv
import io
import os
import base64
import bcrypt
from jose import jwt, JWTError

# driver do Postgres — OPCIONAL (só usado quando o app roda contra o Supabase/nuvem).
# Sem ele instalado, o app roda no SQLite local normalmente.
try:
    import psycopg2
except ImportError:
    psycopg2 = None

# leitor de conta por imagem/PDF (OCR) — dependência OPCIONAL.
# se pytesseract/Pillow/PyMuPDF não estiverem instalados, o app inteiro continua
# funcionando normalmente; só a rota /importar/conta-imagem fica indisponível.
# ver estudo_ocr_conta_imagem.md para instruções de instalação.
try:
    import pytesseract
    from PIL import Image, ImageOps
    import pymupdf as fitz  # PyMuPDF; "pymupdf" é o nome novo do pacote, "fitz" é só o alias de import
    OCR_DISPONIVEL = True
except ImportError:
    OCR_DISPONIVEL = False

# caminho do executável do Tesseract e pasta de idiomas (.traineddata).
# Ordem de resolução da pasta de idiomas (a primeira que existir vence):
#   1) variável de ambiente TESSDATA_DIR (se o usuário quiser forçar um caminho);
#   2) uma pasta "tessdata" ao lado deste main.py (jeito portável: os idiomas viajam
#      junto com o app, sem precisar de admin pra gravar em Program Files);
#   3) None -> o Tesseract usa a pasta padrão da própria instalação (Program Files\
#      Tesseract-OCR\tessdata), que já vem com o inglês.
# Isso resolve o caso de não ter permissão de admin pra pôr o por.traineddata na
# pasta padrão do Tesseract (aconteceu nesta máquina).
if OCR_DISPONIVEL:
    pytesseract.pytesseract.tesseract_cmd = os.environ.get(
        "TESSERACT_CMD", r"C:\Program Files\Tesseract-OCR\tesseract.exe"
    )
    _tessdata_local = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tessdata")
    TESSDATA_DIR = os.environ.get("TESSDATA_DIR") or (
        _tessdata_local if os.path.isdir(_tessdata_local) else None
    )

app = FastAPI()
seguranca = HTTPBearer(auto_error=False)


# ========================================================
# FUNÇÕES DE APOIO (banco e cálculos) — ficam antes das rotas
# ========================================================

# ========================================================
# BACKEND DE BANCO: SQLite (local) OU Postgres/Supabase (nuvem)
# --------------------------------------------------------
# Se houver PGHOST (ou DATABASE_URL) no ambiente, o app fala com o Postgres do
# Supabase; senão, usa o arquivo SQLite local (financeiro.db), como sempre.
# O mesmo código roda nos dois lugares — um wrapper traduz os placeholders '?' -> '%s'.
# ========================================================

def _carregar_env_local():
    # No Render as variáveis vêm do painel (já estão em os.environ). Localmente, carrega
    # um .env ao lado deste arquivo, se existir — sem sobrescrever o que já veio do ambiente.
    caminho = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
    if not os.path.exists(caminho):
        return
    for linha in open(caminho, encoding="utf-8"):
        linha = linha.strip()
        if not linha or linha.startswith("#") or "=" not in linha:
            continue
        chave, valor = linha.split("=", 1)
        os.environ.setdefault(chave.strip(), valor.strip().strip("'").strip('"'))

_carregar_env_local()
USA_POSTGRES = bool(os.environ.get("PGHOST") or os.environ.get("DATABASE_URL"))

# DDL do Postgres (schema completo, já com as colunas que o migrar() adiciona no SQLite).
DDL_POSTGRES = [
    "CREATE TABLE IF NOT EXISTS bancos (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome TEXT, user_id UUID)",
    "CREATE TABLE IF NOT EXISTS caixinhas (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome TEXT, banco_id BIGINT, meta_centavos BIGINT DEFAULT 0, meta_prazo TEXT, user_id UUID)",
    "CREATE TABLE IF NOT EXISTS lancamentos (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tipo TEXT, valor_centavos BIGINT, descricao TEXT, caixinha_id BIGINT, data TEXT, user_id UUID)",
    "CREATE TABLE IF NOT EXISTS contas (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome TEXT, valor_centavos BIGINT, vencimento TEXT, tipo TEXT, paga INTEGER DEFAULT 0, caixinha_paga_id BIGINT, tipo_conta TEXT DEFAULT 'simples', arquivada INTEGER DEFAULT 0, user_id UUID)",
    "CREATE TABLE IF NOT EXISTS recorrentes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome TEXT, valor_centavos BIGINT, dia_vencimento INTEGER, tipo TEXT, conta_fatura_id BIGINT, user_id UUID)",
    "CREATE TABLE IF NOT EXISTS config (user_id UUID, chave TEXT, valor TEXT, PRIMARY KEY (user_id, chave))",
    "CREATE TABLE IF NOT EXISTS fatura_itens (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, conta_id BIGINT, descricao TEXT, valor_centavos BIGINT, data TEXT, user_id UUID)",
    "CREATE TABLE IF NOT EXISTS categorias (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome TEXT, user_id UUID)",
    "CREATE TABLE IF NOT EXISTS regras_salario (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, gatilho TEXT, modo TEXT, valor BIGINT, caixinha_id BIGINT, user_id UUID)",
    "CREATE INDEX IF NOT EXISTS bancos_user_idx ON bancos(user_id)",
    "CREATE INDEX IF NOT EXISTS caixinhas_user_idx ON caixinhas(user_id)",
    "CREATE INDEX IF NOT EXISTS lancamentos_user_idx ON lancamentos(user_id)",
    "CREATE INDEX IF NOT EXISTS contas_user_idx ON contas(user_id)",
    "CREATE INDEX IF NOT EXISTS recorrentes_user_idx ON recorrentes(user_id)",
    "CREATE INDEX IF NOT EXISTS fatura_itens_user_idx ON fatura_itens(user_id)",
    "CREATE INDEX IF NOT EXISTS categorias_user_idx ON categorias(user_id)",
    "CREATE INDEX IF NOT EXISTS regras_salario_user_idx ON regras_salario(user_id)",
]

class _ConexaoPG:
    """Faz a conexão psycopg2 se comportar como a do sqlite3 que o código usa:
    con.execute("... ?", (...)).fetchone()/fetchall(), con.commit(), con.close().
    Traduz '?' -> '%s' e devolve um cursor a cada execute."""
    def __init__(self):
        if psycopg2 is None:
            raise RuntimeError("psycopg2 não instalado — rode: pip install psycopg2-binary")
        self._con = psycopg2.connect(
            host=os.environ["PGHOST"],
            port=os.environ.get("PGPORT", "5432"),
            dbname=os.environ.get("PGDATABASE", "postgres"),
            user=os.environ["PGUSER"],
            password=os.environ["PGPASSWORD"],
            sslmode=os.environ.get("PGSSLMODE", "require"),
        )
    def execute(self, sql, params=()):
        cur = self._con.cursor()
        cur.execute(sql.replace("?", "%s"), params)
        return cur
    def commit(self):
        self._con.commit()
    def close(self):
        self._con.close()

def conectar():
    if USA_POSTGRES:
        return _ConexaoPG()
    return sqlite3.connect("financeiro.db")

# INSERT-ou-atualiza uma chave da config (dialetos diferentes entre SQLite e Postgres).
def _upsert_config(con, user_id, chave, valor):
    if USA_POSTGRES:
        con.execute("INSERT INTO config (user_id, chave, valor) VALUES (?, ?, ?) "
                    "ON CONFLICT (user_id, chave) DO UPDATE SET valor = EXCLUDED.valor", (user_id, chave, valor))
    else:
        con.execute("INSERT OR REPLACE INTO config (user_id, chave, valor) VALUES (?, ?, ?)", (user_id, chave, valor))

def criar_tabelas():
    con = conectar()
    # No Postgres a DDL já cria o schema completo (com todas as colunas); semeia e sai.
    if USA_POSTGRES:
        for ddl in DDL_POSTGRES:
            con.execute(ddl)
        con.commit()
        con.close()
        migrar()
        return
    con.execute("""
        CREATE TABLE IF NOT EXISTS bancos (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            nome TEXT
        )
    """)
    con.execute("""
        CREATE TABLE IF NOT EXISTS caixinhas (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            nome TEXT
        )
    """)
    con.execute("""
        CREATE TABLE IF NOT EXISTS lancamentos (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            tipo TEXT,
            valor_centavos INTEGER,
            descricao TEXT,
            caixinha_id INTEGER
        )
    """)
    con.execute("""
        CREATE TABLE IF NOT EXISTS contas (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            nome TEXT,
            valor_centavos INTEGER,
            vencimento TEXT,
            tipo TEXT,
            paga INTEGER DEFAULT 0,
            caixinha_paga_id INTEGER
        )
    """)
    con.execute("""
        CREATE TABLE IF NOT EXISTS recorrentes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            nome TEXT,
            valor_centavos INTEGER,
            dia_vencimento INTEGER,
            tipo TEXT
        )
    """)
    con.execute("""
        CREATE TABLE IF NOT EXISTS config (
            user_id TEXT,
            chave TEXT,
            valor TEXT,
            PRIMARY KEY (user_id, chave)
        )
    """)
    # D: itens de uma conta do tipo "fatura" (cartão). O total da fatura é a soma destes itens.
    con.execute("""
        CREATE TABLE IF NOT EXISTS fatura_itens (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            conta_id INTEGER,
            descricao TEXT,
            valor_centavos INTEGER,
            data TEXT
        )
    """)
    # Categorias das contas (rótulos gerenciáveis pelo usuário: fixa, cartão, etc.).
    con.execute("""
        CREATE TABLE IF NOT EXISTS categorias (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            nome TEXT
        )
    """)
    # E4: regras de salário — quando uma entrada com certo nome é registrada,
    # guarda automaticamente uma % ou valor fixo numa caixinha.
    # modo = 'percentual' (valor = % inteiro) ou 'fixo' (valor = centavos).
    con.execute("""
        CREATE TABLE IF NOT EXISTS regras_salario (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            gatilho TEXT,
            modo TEXT,
            valor INTEGER,
            caixinha_id INTEGER
        )
    """)
    # (categorias padrão agora são semeadas POR USUÁRIO em _garantir_usuario)
    con.commit()
    con.close()
    migrar()

# adiciona colunas novas a tabelas que já existem, sem apagar dados.
# só adiciona se a coluna ainda não existir (senão o ALTER daria erro na 2ª vez).
def migrar():
    if USA_POSTGRES:
        return  # no Postgres a DDL de criar_tabelas() já cria as tabelas completas
    con = conectar()
    # quais colunas a tabela caixinhas já tem?
    colunas = [c[1] for c in con.execute("PRAGMA table_info(caixinhas)").fetchall()]
    if "banco_id" not in colunas:
        con.execute("ALTER TABLE caixinhas ADD COLUMN banco_id INTEGER")
    # F1: passar a guardar a DATA de cada lançamento (só os novos terão data;
    # os antigos ficam com NULL, pois não dá pra inventar quando aconteceram).
    colunas_lanc = [c[1] for c in con.execute("PRAGMA table_info(lancamentos)").fetchall()]
    if "data" not in colunas_lanc:
        con.execute("ALTER TABLE lancamentos ADD COLUMN data TEXT")
    # D: tipo da conta — "simples" (valor único) ou "fatura" (soma de itens).
    # Contas antigas assumem "simples" (DEFAULT), preservando o comportamento atual.
    colunas_contas = [c[1] for c in con.execute("PRAGMA table_info(contas)").fetchall()]
    if "tipo_conta" not in colunas_contas:
        con.execute("ALTER TABLE contas ADD COLUMN tipo_conta TEXT DEFAULT 'simples'")
    # Metas: valor-alvo opcional de cada caixinha (0 = sem meta).
    if "meta_centavos" not in colunas:
        con.execute("ALTER TABLE caixinhas ADD COLUMN meta_centavos INTEGER DEFAULT 0")
    # E8: data-limite opcional da meta (AAAA-MM-DD). Vazio = meta sem prazo.
    if "meta_prazo" not in colunas:
        con.execute("ALTER TABLE caixinhas ADD COLUMN meta_prazo TEXT")
    # M1: arquivar (não apagar) contas pagas pra limpar a tela sem perder o histórico.
    if "arquivada" not in colunas_contas:
        con.execute("ALTER TABLE contas ADD COLUMN arquivada INTEGER DEFAULT 0")
    # E2: vínculo da assinatura com uma fatura de cartão (FK). Vazio = conta avulsa.
    colunas_rec = [c[1] for c in con.execute("PRAGMA table_info(recorrentes)").fetchall()]
    if "conta_fatura_id" not in colunas_rec:
        con.execute("ALTER TABLE recorrentes ADD COLUMN conta_fatura_id INTEGER")
    # multi-usuário: user_id em todas as tabelas de dados (SQLite local)
    for _t in ("bancos", "caixinhas", "lancamentos", "contas", "recorrentes", "fatura_itens", "categorias", "regras_salario"):
        _cols = [c[1] for c in con.execute(f"PRAGMA table_info({_t})").fetchall()]
        if "user_id" not in _cols:
            con.execute(f"ALTER TABLE {_t} ADD COLUMN user_id TEXT")
    con.commit()
    con.close()

# ---- autenticação: Supabase Auth ----
# O front faz login no Supabase (e-mail/senha; signups desativados no painel) e envia o
# access_token (JWT) no header Authorization. Aqui a gente VERIFICA esse token e extrai o
# `sub` = UUID do usuário. Projetos novos do Supabase assinam com ES256 (chave assimétrica,
# publicada no JWKS); os antigos usam HS256 (a JWT Secret). Suportamos os dois.

SUPABASE_URL = os.environ.get("SUPABASE_URL", "").rstrip("/")
SUPABASE_PUBLISHABLE_KEY = os.environ.get("SUPABASE_PUBLISHABLE_KEY", "")
SUPABASE_JWT_SECRET = os.environ.get("SUPABASE_JWT_SECRET")

# JWKS do Supabase (chaves públicas ES256) — buscado 1x e cacheado.
_jwks_cache = None
def _supabase_jwks():
    global _jwks_cache
    if _jwks_cache is None and SUPABASE_URL:
        import urllib.request, json as _json
        try:
            req = urllib.request.Request(
                SUPABASE_URL + "/auth/v1/.well-known/jwks.json",
                headers={"apikey": SUPABASE_PUBLISHABLE_KEY} if SUPABASE_PUBLISHABLE_KEY else {},
            )
            with urllib.request.urlopen(req, timeout=10) as r:
                _jwks_cache = _json.loads(r.read().decode())
        except Exception:
            _jwks_cache = None
    return _jwks_cache

def _verificar_token(tok):
    """Verifica o access_token do Supabase: tenta ES256 (JWKS) e cai pra HS256 (JWT Secret)."""
    global _jwks_cache
    try:
        kid = jwt.get_unverified_header(tok).get("kid")
    except Exception:
        kid = None
    for tentativa in (1, 2):
        jwks = _supabase_jwks()
        if jwks:
            keys = jwks.get("keys", [])
            chave = next((k for k in keys if k.get("kid") == kid), None) or (keys[0] if keys else None)
            if chave:
                try:
                    return jwt.decode(tok, chave, algorithms=["ES256"], audience="authenticated")
                except JWTError:
                    pass
        if tentativa == 1:
            _jwks_cache = None  # a chave pode ter rotacionado; recarrega o JWKS uma vez
    if SUPABASE_JWT_SECRET:
        return jwt.decode(tok, SUPABASE_JWT_SECRET, algorithms=["HS256"], audience="authenticated")
    raise JWTError("nenhuma chave disponível para verificar o token")

_usuarios_prontos = set()  # cache dos usuários que já receberam suas categorias padrão

def _garantir_usuario(user_id):
    # semeia as categorias padrão UMA vez por usuário (na 1ª vez que ele acessa)
    if user_id in _usuarios_prontos:
        return
    con = conectar()
    ja = con.execute(
        "SELECT valor FROM config WHERE user_id=? AND chave='categorias_iniciadas'", (user_id,)
    ).fetchone()
    if ja is None:
        for nome in ("Conta fixa", "Cartão", "Outros"):
            con.execute("INSERT INTO categorias (nome, user_id) VALUES (?, ?)", (nome, user_id))
        _upsert_config(con, user_id, "categorias_iniciadas", "1")
        con.commit()
    con.close()
    _usuarios_prontos.add(user_id)

# dependência que protege as rotas: exige um token válido do Supabase e devolve o user_id
def exigir_login(cred: HTTPAuthorizationCredentials = Depends(seguranca)):
    if cred is None:
        raise HTTPException(status_code=401, detail="Não autenticado.")
    try:
        dados = _verificar_token(cred.credentials)
    except Exception:
        raise HTTPException(status_code=401, detail="Sessão inválida ou expirada.")
    user_id = dados.get("sub")
    if not user_id:
        raise HTTPException(status_code=401, detail="Token sem usuário.")
    _garantir_usuario(user_id)
    return user_id

criar_tabelas()

# data de hoje no formato AAAA-MM-DD, usada ao gravar cada lançamento novo (F1)
def data_hoje():
    return date.today().isoformat()

# valida uma data recebida: vazia (usa hoje) OU no formato AAAA-MM-DD com ano plausível.
# evita "datas malucas" (ex.: ano 1990, texto solto) que quebrariam agrupamentos/ordem.
def data_valida(s):
    if not s:
        return True
    m = re.match(r"^(\d{4})-(\d{2})-(\d{2})$", s)
    if not m:
        return False
    ano, mes, dia = int(m.group(1)), int(m.group(2)), int(m.group(3))
    if not (2000 <= ano <= 2100 and 1 <= mes <= 12 and 1 <= dia <= 31):
        return False
    return True

# saldo de uma caixinha = (alocações + rendimentos) menos pagamentos dela.
# M2: 'rendimento' (ex.: CDI) entra na caixinha como dinheiro novo — por isso soma aqui,
# mas NÃO conta como 'entrada' (não infla "Entrou no mês") nem sai do saldo livre.
def saldo_da_caixinha(con, user_id, caixinha_id):
    entrou = con.execute(
        "SELECT COALESCE(SUM(valor_centavos),0) FROM lancamentos WHERE caixinha_id=? AND user_id=? AND tipo IN ('alocacao','rendimento')",
        (caixinha_id, user_id)
    ).fetchone()[0]
    saiu = con.execute(
        "SELECT COALESCE(SUM(valor_centavos),0) FROM lancamentos WHERE caixinha_id=? AND user_id=? AND tipo='pagamento'",
        (caixinha_id, user_id)
    ).fetchone()[0]
    return entrou - saiu

# D: total de uma conta. Fatura = soma dos itens; simples = o valor guardado.
def total_conta(con, user_id, conta_id, tipo_conta, valor_centavos):
    if tipo_conta == "fatura":
        return con.execute(
            "SELECT COALESCE(SUM(valor_centavos),0) FROM fatura_itens WHERE conta_id=? AND user_id=?",
            (conta_id, user_id)
        ).fetchone()[0]
    return valor_centavos

# E4: aplica as regras de salário a uma entrada recém-registrada.
# Para cada regra cujo gatilho bate (ignora maiúsc/minúsc) com a descrição da entrada,
# cria uma alocação automática na caixinha indicada (% do valor ou valor fixo).
def aplicar_regras_salario(con, user_id, descricao, valor_centavos, data):
    alvo = (descricao or "").strip().lower()
    if not alvo:
        return
    regras = con.execute(
        "SELECT modo, valor, caixinha_id FROM regras_salario WHERE user_id=? AND lower(gatilho)=?",
        (user_id, alvo)
    ).fetchall()
    for modo, valor, cxid in regras:
        if cxid is None:
            continue
        existe = con.execute("SELECT id FROM caixinhas WHERE id=? AND user_id=?", (cxid, user_id)).fetchone()
        if existe is None:
            continue
        if modo == "percentual":
            quantia = round(valor_centavos * valor / 100)
        else:
            quantia = valor
        if quantia <= 0:
            continue
        con.execute(
            "INSERT INTO lancamentos (tipo, valor_centavos, descricao, caixinha_id, data, user_id) VALUES ('alocacao', ?, ?, ?, ?, ?)",
            (quantia, f"regra: {descricao.strip()}", cxid, data, user_id)
        )

# gera as cobranças das recorrentes para o mês atual (uma vez por mês, sem duplicar).
# E2: se a assinatura está vinculada a uma fatura de cartão, ela entra como ITEM dessa
# fatura (soma no cartão) em vez de virar uma conta avulsa. Se estiver avulsa, cria a conta.
def gerar_recorrentes_do_mes(user_id):
    con = conectar()
    hoje = date.today()
    ano = hoje.year
    mes = hoje.month
    mes_str = f"{ano:04d}-{mes:02d}"
    recorrentes = con.execute(
        "SELECT nome, valor_centavos, dia_vencimento, tipo, conta_fatura_id FROM recorrentes WHERE user_id=?",
        (user_id,)
    ).fetchall()
    for nome, valor, dia, tipo, fatura_id in recorrentes:
        vencimento = f"{ano:04d}-{mes:02d}-{dia:02d}"
        if fatura_id is not None:
            fatura = con.execute(
                "SELECT id, tipo_conta, paga FROM contas WHERE id=? AND user_id=?", (fatura_id, user_id)
            ).fetchone()
            # vinculada a uma fatura VÁLIDA -> vira item dela (nunca cria conta avulsa)
            if fatura is not None and (fatura[1] or "simples") == "fatura":
                if fatura[2] == 0:  # só mexe na fatura se ainda não foi paga
                    ja_item = con.execute(
                        "SELECT id FROM fatura_itens WHERE conta_id=? AND descricao=? AND data LIKE ? AND user_id=?",
                        (fatura_id, nome, mes_str + "%", user_id)
                    ).fetchone()
                    if ja_item is None:
                        con.execute(
                            "INSERT INTO fatura_itens (conta_id, descricao, valor_centavos, data, user_id) VALUES (?, ?, ?, ?, ?)",
                            (fatura_id, nome, valor, vencimento, user_id)
                        )
                continue
            # fatura apagada ou inválida -> cai no comportamento avulso abaixo
        ja_existe = con.execute(
            "SELECT id FROM contas WHERE nome=? AND vencimento=? AND user_id=?",
            (nome, vencimento, user_id)
        ).fetchone()
        if ja_existe is None:
            con.execute(
                "INSERT INTO contas (nome, valor_centavos, vencimento, tipo, user_id) VALUES (?, ?, ?, ?, ?)",
                (nome, valor, vencimento, tipo, user_id)
            )
    con.commit()
    con.close()


# ========================================================
# E3: LEITOR DE EXTRATO (OFX / CSV) — sem bibliotecas externas.
# Lê o texto do arquivo, extrai (descrição, valor, data) e tenta adivinhar a caixinha.
# Não guarda nada sozinho: devolve uma prévia para o usuário revisar e confirmar.
# ========================================================

# palavra na descrição -> nome de categoria/caixinha provável
MAPA_PALAVRAS = {
    "uber": "transporte", "99": "transporte", "99pop": "transporte", "cabify": "transporte",
    "posto": "transporte", "combustivel": "transporte", "gasolina": "transporte", "ipva": "transporte",
    "ifood": "alimentação", "rappi": "alimentação", "mercado": "alimentação", "supermercado": "alimentação",
    "restaurante": "alimentação", "padaria": "alimentação", "lanche": "alimentação", "acougue": "alimentação",
    "netflix": "assinaturas", "spotify": "assinaturas", "amazon": "assinaturas", "prime": "assinaturas",
    "disney": "assinaturas", "youtube": "assinaturas", "hbo": "assinaturas",
    "farmacia": "saúde", "drogaria": "saúde", "hospital": "saúde", "clinica": "saúde",
    "luz": "contas", "energia": "contas", "agua": "contas", "internet": "contas",
    "telefone": "contas", "aluguel": "contas", "condominio": "contas",
}

def _num_br(s):
    """Converte um texto monetário (formatos BR e US) em float, ou None se não for número."""
    s = (s or "").strip().replace("R$", "").replace(" ", "")
    if not s:
        return None
    neg = s.startswith("-") or s.startswith("(")
    s2 = s.replace("(", "").replace(")", "").replace("+", "").lstrip("-")
    if "," in s2 and "." in s2:
        s2 = s2.replace(".", "").replace(",", ".")   # 1.234,56 -> 1234.56
    elif "," in s2:
        s2 = s2.replace(",", ".")                     # 1234,56 -> 1234.56
    try:
        v = float(s2)
    except ValueError:
        return None
    return -v if neg else v

def _data_iso(s):
    """Normaliza datas comuns (dd/mm/aaaa, aaaa-mm-dd, dd/mm/aa) para AAAA-MM-DD, ou '?'."""
    s = (s or "").strip()
    m = re.match(r"^(\d{2})/(\d{2})/(\d{4})$", s)
    if m:
        return f"{m.group(3)}-{m.group(2)}-{m.group(1)}"
    if re.match(r"^\d{4}-\d{2}-\d{2}$", s):
        return s
    m = re.match(r"^(\d{2})/(\d{2})/(\d{2})$", s)
    if m:
        return f"20{m.group(3)}-{m.group(2)}-{m.group(1)}"
    return "?"

def _sugerir_caixinha(descricao, caixinhas):
    """caixinhas = lista de (id, nome_minusculo). Retorna o id sugerido ou None."""
    d = (descricao or "").lower()
    for cid, nome in caixinhas:
        if nome and nome in d:
            return cid
    for palavra, categoria in MAPA_PALAVRAS.items():
        if palavra in d:
            for cid, nome in caixinhas:
                if nome == categoria:
                    return cid
    return None

def parse_ofx(texto, caixinhas):
    linhas = []
    for bloco in re.findall(r"<STMTTRN>(.*?)</STMTTRN>", texto, re.S | re.I):
        m_val = re.search(r"<TRNAMT>([^<\r\n]+)", bloco, re.I)
        if not m_val:
            continue
        valor = _num_br(m_val.group(1))
        if valor is None:
            continue
        m_dt = re.search(r"<DTPOSTED>(\d{8})", bloco, re.I)
        data = "?"
        if m_dt:
            g = m_dt.group(1)
            data = f"{g[0:4]}-{g[4:6]}-{g[6:8]}"
        m_memo = re.search(r"<MEMO>([^<\r\n]+)", bloco, re.I)
        m_name = re.search(r"<NAME>([^<\r\n]+)", bloco, re.I)
        desc = (m_memo.group(1) if m_memo else (m_name.group(1) if m_name else "lançamento")).strip()
        cents = abs(round(valor * 100))
        if cents == 0:
            continue
        linhas.append({
            "descricao": desc[:80],
            "valor_centavos": cents,
            "data": data,
            "tipo": "entrada" if valor > 0 else "pagamento",
            "caixinha_id": _sugerir_caixinha(desc, caixinhas),
        })
    return linhas

def parse_csv(texto, caixinhas):
    amostra = texto[:3000]
    delim = ";" if amostra.count(";") >= amostra.count(",") else ","
    linhas_raw = [r for r in csv.reader(io.StringIO(texto), delimiter=delim) if any((c or "").strip() for c in r)]
    if not linhas_raw:
        return []

    def achar(hs, termos):
        for i, h in enumerate(hs):
            for t in termos:
                if t in h:
                    return i
        return None

    header = [(c or "").strip().lower() for c in linhas_raw[0]]
    i_data = achar(header, ["data", "date"])
    i_valor = achar(header, ["valor", "amount", "quantia", "montante", "value"])
    i_desc = achar(header, ["descri", "histor", "lanç", "lanc", "memo", "estabelec", "title", "detalhe"])
    tem_cabecalho = (i_data is not None) or (i_valor is not None)
    corpo = linhas_raw[1:] if tem_cabecalho else linhas_raw

    linhas = []
    for r in corpo:
        valor = None
        data = "?"
        desc = "lançamento"
        if i_valor is not None and i_valor < len(r):
            valor = _num_br(r[i_valor])
            if i_data is not None and i_data < len(r):
                data = _data_iso(r[i_data])
            if i_desc is not None and i_desc < len(r):
                desc = (r[i_desc] or "").strip() or "lançamento"
        else:
            # heurística posicional: acha um token de data e um token monetário (com , ou .)
            partes = []
            for cel in r:
                c = (cel or "").strip()
                if data == "?" and _data_iso(c) != "?":
                    data = _data_iso(c); continue
                if valor is None and ("," in c or "." in c) and _num_br(c) is not None:
                    valor = _num_br(c); continue
                partes.append(c)
            desc = " ".join(p for p in partes if p) or "lançamento"
        if valor is None:
            continue
        cents = abs(round(valor * 100))
        if cents == 0:
            continue
        linhas.append({
            "descricao": desc[:80],
            "valor_centavos": cents,
            "data": data,
            "tipo": "entrada" if valor > 0 else "pagamento",
            "caixinha_id": _sugerir_caixinha(desc, caixinhas),
        })
    return linhas


# ========================================================
# LEITOR DE CONTA POR IMAGEM/PDF (OCR) — sub-item de E3, ver estudo_ocr_conta_imagem.md.
# Lê a imagem/PDF, extrai texto (OCR local via Tesseract, sem nuvem/IA) e tenta achar
# valor + vencimento por regex. Igual ao importador de extrato: NUNCA grava sozinho,
# só devolve uma prévia editável — quem cria a conta de fato é o /contas já existente.
# ========================================================

TAMANHO_MAX_ARQUIVO_OCR = 15 * 1024 * 1024  # 15 MB — evita foto gigante travando o OCR

def _config_tesseract():
    # pytesseract passa este texto direto pro subprocesso (sem shell), então NÃO envolver
    # o caminho em aspas aqui — isso faria as aspas virarem parte literal do caminho.
    if TESSDATA_DIR:
        return f"--tessdata-dir {TESSDATA_DIR}"
    return ""

def _idiomas_ocr():
    """'por+eng' se o português estiver disponível; senão cai pra 'eng' sozinho.
    Evita quebrar o OCR quando só o inglês (que já vem com o Tesseract) está instalado —
    números e datas, que é o que mais importa aqui, saem bem só com inglês."""
    pasta = TESSDATA_DIR or os.path.join(
        os.path.dirname(pytesseract.pytesseract.tesseract_cmd), "tessdata"
    )
    if os.path.isfile(os.path.join(pasta, "por.traineddata")):
        return "por+eng"
    return "eng"

def _preprocessar_imagem(img):
    """Escala de cinza + auto-contraste; amplia foto pequena. Ajuda bastante o OCR,
    mas não substitui uma foto bem tirada (reta, sem sombra) — ver 'Realidade' no estudo."""
    img = img.convert("L")
    img = ImageOps.autocontrast(img)
    if img.width < 1000:
        fator = 1600 / max(img.width, 1)
        img = img.resize((int(img.width * fator), int(img.height * fator)), Image.LANCZOS)
    return img

def _ocr_imagem_pil(img):
    img = _preprocessar_imagem(img)
    return pytesseract.image_to_string(img, lang=_idiomas_ocr(), config=_config_tesseract())

def ocr_texto_imagem(bytes_imagem):
    img = Image.open(io.BytesIO(bytes_imagem))
    return _ocr_imagem_pil(img)

def ocr_texto_pdf(bytes_pdf):
    """PDF 'de texto' (a maioria de boletos gerados por sistema): lê direto, sem OCR.
    PDF escaneado (foto virou PDF): a página não tem texto -> renderiza como imagem e faz OCR."""
    doc = fitz.open(stream=bytes_pdf, filetype="pdf")
    partes = []
    for pagina in doc:
        texto = pagina.get_text().strip()
        if len(texto) >= 30:
            partes.append(texto)
        else:
            pix = pagina.get_pixmap(dpi=300)
            img = Image.frombytes("RGB", (pix.width, pix.height), pix.samples)
            partes.append(_ocr_imagem_pil(img))
    doc.close()
    return "\n".join(partes)

# termos de contexto que aumentam a confiança de que aquele número/data é o que queremos
_TERMOS_VALOR = ["valor a pagar", "total a pagar", "valor cobrado", "valor do documento", "total geral", "valor total", "total"]
_TERMOS_VENCIMENTO = ["vencimento", "vence em", "pagamento até", "pague até", "válido até", "data limite"]

# nomes prováveis pela palavra encontrada no texto (mesma ideia do MAPA_PALAVRAS do importador de extrato)
_MAPA_NOME_CONTA = {
    "energia": "Energia", "eletrica": "Energia", "elétrica": "Energia", "enel": "Energia", "cpfl": "Energia", "light": "Energia",
    "água": "Água", "agua": "Água", "saneamento": "Água", "sabesp": "Água",
    "internet": "Internet", "banda larga": "Internet", "fibra": "Internet",
    "telefone": "Telefone", "celular": "Telefone",
    "condomínio": "Condomínio", "condominio": "Condomínio",
    "aluguel": "Aluguel",
    "cartão": "Cartão", "cartao": "Cartão", "fatura": "Cartão",
    "gás": "Gás", "gas": "Gás", "comgas": "Gás",
}

def _melhor_valor(texto):
    """Acha 'R$ x,xx' no texto; prioriza o que estiver perto (60 chars antes) de um termo
    tipo 'valor a pagar'/'total'. Sem contexto, usa o maior valor encontrado (heurística:
    o total costuma ser o maior número monetário da conta)."""
    candidatos = []
    for m in re.finditer(r"(?:R\$\s*)?(\d{1,3}(?:\.\d{3})*,\d{2})", texto):
        valor = _num_br(m.group(1))
        if valor is None or valor <= 0:
            continue
        contexto = texto[max(0, m.start() - 60):m.start()].lower()
        prioridade = any(t in contexto for t in _TERMOS_VALOR)
        candidatos.append((prioridade, valor, m.group(1)))
    if not candidatos:
        return None
    com_contexto = [c for c in candidatos if c[0]]
    escolhidos = com_contexto if com_contexto else candidatos
    return max(escolhidos, key=lambda c: c[1])[1]

def _melhor_vencimento(texto):
    """Acha datas dd/mm/aaaa; prioriza a que estiver perto de 'vencimento'/'vence em' etc."""
    candidatos = []
    for m in re.finditer(r"\b(\d{2}/\d{2}/\d{4})\b", texto):
        iso = _data_iso(m.group(1))
        if iso == "?":
            continue
        contexto = texto[max(0, m.start() - 40):m.start()].lower()
        prioridade = any(t in contexto for t in _TERMOS_VENCIMENTO)
        candidatos.append((prioridade, m.start(), iso))
    if not candidatos:
        return "?"
    com_contexto = [c for c in candidatos if c[0]]
    escolhidos = com_contexto if com_contexto else candidatos
    return min(escolhidos, key=lambda c: c[1])[2]  # a primeira ocorrência, entre as prioritárias

def _sugerir_nome_conta(texto):
    t = texto.lower()
    for palavra, nome in _MAPA_NOME_CONTA.items():
        if palavra in t:
            return nome
    return "Conta"

def extrair_conta(texto):
    valor = _melhor_valor(texto)
    return {
        "nome": _sugerir_nome_conta(texto),
        "valor_centavos": round(valor * 100) if valor else 0,
        "vencimento": _melhor_vencimento(texto),
        "texto_bruto": texto.strip()[:4000],  # limitado pra não inchar a resposta
    }


# ========================================================
# MODELOS (o formato do que chega em cada rota) — todos juntos
# ========================================================

class NovaCaixinha(BaseModel):
    nome: str
    banco_id: int
    meta_centavos: int = 0   # meta opcional (0 = sem meta)

class DefinirMeta(BaseModel):
    meta_centavos: int
    meta_prazo: str | None = None   # E8: data-limite opcional (AAAA-MM-DD)

class MoverCaixinha(BaseModel):
    banco_id: int

class NovoLancamento(BaseModel):
    tipo: str
    valor_centavos: int
    descricao: str
    caixinha_id: int | None = None
    data: str | None = None   # data escolhida (AAAA-MM-DD); se vazio, usa hoje

class NovaTransferencia(BaseModel):
    origem_id: int
    destino_id: int
    valor_centavos: int

class NovaConta(BaseModel):
    nome: str
    valor_centavos: int
    vencimento: str
    tipo: str
    tipo_conta: str = "simples"   # D: "simples" ou "fatura"

class EditarConta(BaseModel):
    nome: str
    valor_centavos: int
    vencimento: str
    tipo: str

class NovoItemFatura(BaseModel):
    descricao: str
    valor_centavos: int

class PagamentoConta(BaseModel):
    caixinha_id: int

class NovaRecorrente(BaseModel):
    nome: str
    valor_centavos: int
    dia_vencimento: int
    tipo: str
    conta_fatura_id: int | None = None   # E2: fatura de cartão vinculada (None = avulsa)

class VincularFatura(BaseModel):
    conta_fatura_id: int | None = None

class NovoBanco(BaseModel):
    nome: str

class NovaCategoria(BaseModel):
    nome: str

class NovaRegra(BaseModel):
    gatilho: str
    modo: str          # 'percentual' (valor = % inteiro) ou 'fixo' (valor = centavos)
    valor: int
    caixinha_id: int

class WrappedVisto(BaseModel):
    mes: str           # "AAAA-MM" do mês cuja retrospectiva já foi mostrada

class ImportarAnalise(BaseModel):
    conteudo: str
    tipo_arquivo: str   # 'ofx' ou 'csv'

class ImportarContaImagem(BaseModel):
    conteudo: str        # data URL completa (data:image/...;base64,XXXX ou data:application/pdf;base64,XXXX)
    tipo_arquivo: str    # 'imagem' ou 'pdf'

class LinhaImport(BaseModel):
    descricao: str
    valor_centavos: int
    data: str
    tipo: str           # 'entrada' ou 'pagamento'
    caixinha_id: int | None = None

class ImportarConfirmar(BaseModel):
    linhas: list[LinhaImport]

class DefinirSenha(BaseModel):
    senha: str

class Login(BaseModel):
    senha: str


# ========================================================
# ROTAS GERAIS
# ========================================================

@app.get("/")
def raiz():
    # a raiz serve o próprio app (front-end). no-store: o navegador não guarda versão antiga.
    return FileResponse("index.html", headers={"Cache-Control": "no-store"})

@app.get("/app")
def servir_pagina():
    # mantém /app funcionando também (mesma página da raiz).
    return FileResponse("index.html", headers={"Cache-Control": "no-store"})

# ---- autenticação ----
# O login é feito pelo Supabase Auth direto no front (o front chama o Supabase e recebe o
# access_token). O back apenas VERIFICA esse token (ver exigir_login). Sem rota de senha aqui.


# ========================================================
# ROTAS DE LANÇAMENTOS
# ========================================================

@app.post("/lancamentos")
def criar_lancamento(item: NovoLancamento, user_id: str = Depends(exigir_login)):
    # validações de entrada
    if item.valor_centavos <= 0:
        raise HTTPException(status_code=400, detail="O valor precisa ser maior que zero.")
    if not data_valida(item.data):
        raise HTTPException(status_code=400, detail="Data inválida (use AAAA-MM-DD, ano entre 2000 e 2100).")
    con = conectar()
    # usa a data escolhida (se veio) ou a de hoje
    data = item.data if item.data else data_hoje()
    con.execute(
        "INSERT INTO lancamentos (tipo, valor_centavos, descricao, caixinha_id, data, user_id) VALUES (?, ?, ?, ?, ?, ?)",
        (item.tipo, item.valor_centavos, item.descricao, item.caixinha_id, data, user_id)
    )
    # E4: entradas disparam as regras de salário (alocações automáticas)
    if item.tipo == "entrada":
        aplicar_regras_salario(con, user_id, item.descricao, item.valor_centavos, data)
    con.commit()
    con.close()
    return {"status": "salvo"}

@app.get("/lancamentos")
def listar_lancamentos(user_id: str = Depends(exigir_login)):
    con = conectar()
    linhas = con.execute("SELECT id, tipo, valor_centavos, descricao, caixinha_id, data FROM lancamentos WHERE user_id=?", (user_id,)).fetchall()
    con.close()
    return [
        {"id": l[0], "tipo": l[1], "valor_reais": l[2] / 100, "descricao": l[3], "caixinha_id": l[4], "data": l[5]}
        for l in linhas
    ]

@app.delete("/lancamentos/{lancamento_id}")
def apagar_lancamento(lancamento_id: int, user_id: str = Depends(exigir_login)):
    con = conectar()
    existe = con.execute("SELECT id FROM lancamentos WHERE id=? AND user_id=?", (lancamento_id, user_id)).fetchone()
    if existe is None:
        con.close()
        raise HTTPException(status_code=404, detail="Esse lançamento não existe.")
    con.execute("DELETE FROM lancamentos WHERE id=? AND user_id=?", (lancamento_id, user_id))
    con.commit()
    con.close()
    return {"status": "lançamento apagado"}

@app.get("/saldo-livre")
def saldo_livre(user_id: str = Depends(exigir_login)):
    con = conectar()
    entradas = con.execute(
        "SELECT COALESCE(SUM(valor_centavos),0) FROM lancamentos WHERE tipo='entrada' AND user_id=?", (user_id,)
    ).fetchone()[0]
    alocado = con.execute(
        "SELECT COALESCE(SUM(valor_centavos),0) FROM lancamentos WHERE tipo='alocacao' AND user_id=?", (user_id,)
    ).fetchone()[0]
    saidas_livres = con.execute(
        "SELECT COALESCE(SUM(valor_centavos),0) FROM lancamentos WHERE tipo='saida_livre' AND user_id=?", (user_id,)
    ).fetchone()[0]
    con.close()
    livre = entradas - alocado - saidas_livres
    return {
        "entradas_reais": entradas / 100,
        "alocado_reais": alocado / 100,
        "saidas_livres_reais": saidas_livres / 100,
        "saldo_livre_reais": livre / 100,
        "tudo_distribuido": livre == 0
    }


# ========================================================
# ROTAS DE CAIXINHAS
# ========================================================

@app.post("/caixinhas")
def criar_caixinha(item: NovaCaixinha, user_id: str = Depends(exigir_login)):
    con = conectar()
    # o banco existe?
    banco = con.execute("SELECT id FROM bancos WHERE id=? AND user_id=?", (item.banco_id, user_id)).fetchone()
    if banco is None:
        con.close()
        raise HTTPException(status_code=400, detail="Esse banco não existe.")
    con.execute(
        "INSERT INTO caixinhas (nome, banco_id, meta_centavos, user_id) VALUES (?, ?, ?, ?)",
        (item.nome, item.banco_id, item.meta_centavos, user_id)
    )
    con.commit()
    con.close()
    return {"status": "caixinha criada"}

@app.get("/caixinhas")
def listar_caixinhas(user_id: str = Depends(exigir_login)):
    con = conectar()
    caixas = con.execute("SELECT id, nome, banco_id, meta_centavos, meta_prazo FROM caixinhas WHERE user_id=?", (user_id,)).fetchall()
    resultado = []
    for c in caixas:
        cid = c[0]
        meta = c[3] or 0
        resultado.append({
            "id": cid,
            "nome": c[1],
            "banco_id": c[2],
            "saldo_reais": saldo_da_caixinha(con, user_id, cid) / 100,
            "meta_reais": (meta / 100) if meta > 0 else None,
            "meta_prazo": c[4]   # E8: data-limite da meta (ou None)
        })
    con.close()
    return resultado

@app.post("/caixinhas/{caixinha_id}/meta")
def definir_meta(caixinha_id: int, item: DefinirMeta, user_id: str = Depends(exigir_login)):
    con = conectar()
    existe = con.execute("SELECT id FROM caixinhas WHERE id=? AND user_id=?", (caixinha_id, user_id)).fetchone()
    if existe is None:
        con.close()
        raise HTTPException(status_code=404, detail="Essa caixinha não existe.")
    meta = item.meta_centavos if item.meta_centavos > 0 else 0
    # sem meta => também zera o prazo; senão grava o prazo informado (ou None)
    prazo = item.meta_prazo if (meta > 0 and item.meta_prazo) else None
    con.execute("UPDATE caixinhas SET meta_centavos=?, meta_prazo=? WHERE id=? AND user_id=?", (meta, prazo, caixinha_id, user_id))
    con.commit()
    con.close()
    return {"status": "meta atualizada"}

@app.post("/caixinhas/{caixinha_id}/mover")
def mover_caixinha(caixinha_id: int, item: MoverCaixinha, user_id: str = Depends(exigir_login)):
    con = conectar()
    existe = con.execute("SELECT id FROM caixinhas WHERE id=? AND user_id=?", (caixinha_id, user_id)).fetchone()
    if existe is None:
        con.close()
        raise HTTPException(status_code=404, detail="Essa caixinha não existe.")
    banco = con.execute("SELECT id FROM bancos WHERE id=? AND user_id=?", (item.banco_id, user_id)).fetchone()
    if banco is None:
        con.close()
        raise HTTPException(status_code=400, detail="Esse banco não existe.")
    con.execute("UPDATE caixinhas SET banco_id=? WHERE id=? AND user_id=?", (item.banco_id, caixinha_id, user_id))
    con.commit()
    con.close()
    return {"status": "caixinha movida"}

@app.post("/transferir")
def transferir(item: NovaTransferencia, user_id: str = Depends(exigir_login)):
    if item.valor_centavos <= 0:
        raise HTTPException(status_code=400, detail="O valor precisa ser maior que zero.")
    if item.origem_id == item.destino_id:
        raise HTTPException(status_code=400, detail="Origem e destino não podem ser a mesma caixinha.")

    con = conectar()

    # origem e destino precisam pertencer ao usuário
    for _cid in (item.origem_id, item.destino_id):
        if con.execute("SELECT id FROM caixinhas WHERE id=? AND user_id=?", (_cid, user_id)).fetchone() is None:
            con.close()
            raise HTTPException(status_code=404, detail="Caixinha não encontrada.")

    saldo_origem = saldo_da_caixinha(con, user_id, item.origem_id)
    if saldo_origem < item.valor_centavos:
        con.close()
        raise HTTPException(status_code=400, detail="Saldo insuficiente na caixinha de origem.")

    # tira da origem (pagamento) e põe no destino (alocacao)
    hoje = data_hoje()
    con.execute(
        "INSERT INTO lancamentos (tipo, valor_centavos, descricao, caixinha_id, data, user_id) VALUES (?, ?, ?, ?, ?, ?)",
        ("pagamento", item.valor_centavos, "transferência (saída)", item.origem_id, hoje, user_id)
    )
    con.execute(
        "INSERT INTO lancamentos (tipo, valor_centavos, descricao, caixinha_id, data, user_id) VALUES (?, ?, ?, ?, ?, ?)",
        ("alocacao", item.valor_centavos, "transferência (entrada)", item.destino_id, hoje, user_id)
    )
    con.commit()
    con.close()
    return {"status": "transferência feita"}

@app.delete("/caixinhas/{caixinha_id}")
def apagar_caixinha(caixinha_id: int, user_id: str = Depends(exigir_login)):
    con = conectar()

    # a caixinha existe?
    existe = con.execute("SELECT id FROM caixinhas WHERE id=? AND user_id=?", (caixinha_id, user_id)).fetchone()
    if existe is None:
        con.close()
        raise HTTPException(status_code=404, detail="Essa caixinha não existe.")

    # tem algum lançamento ligado a ela?
    qtd = con.execute(
        "SELECT COUNT(*) FROM lancamentos WHERE caixinha_id=? AND user_id=?",
        (caixinha_id, user_id)
    ).fetchone()[0]
    if qtd > 0:
        con.close()
        raise HTTPException(
            status_code=400,
            detail="A caixinha tem lançamentos. Transfira o saldo para outra antes de apagar."
        )

    con.execute("DELETE FROM caixinhas WHERE id=? AND user_id=?", (caixinha_id, user_id))
    con.commit()
    con.close()
    return {"status": "caixinha apagada"}


# ========================================================
# ROTAS DE CONTAS / DÍVIDAS
# ========================================================

@app.post("/contas")
def criar_conta(item: NovaConta, user_id: str = Depends(exigir_login)):
    # validações: conta simples precisa de valor > 0; vencimento (se veio) tem que ser data válida
    if item.tipo_conta != "fatura" and item.valor_centavos <= 0:
        raise HTTPException(status_code=400, detail="O valor da conta precisa ser maior que zero.")
    if not data_valida(item.vencimento):
        raise HTTPException(status_code=400, detail="Vencimento inválido (use AAAA-MM-DD, ano entre 2000 e 2100).")
    con = conectar()
    # fatura nasce com total 0 (o valor vem da soma dos itens); simples usa o valor informado.
    valor = 0 if item.tipo_conta == "fatura" else item.valor_centavos
    con.execute(
        "INSERT INTO contas (nome, valor_centavos, vencimento, tipo, tipo_conta, user_id) VALUES (?, ?, ?, ?, ?, ?)",
        (item.nome, valor, item.vencimento, item.tipo, item.tipo_conta, user_id)
    )
    con.commit()
    con.close()
    return {"status": "conta criada"}

@app.delete("/contas/{conta_id}")
def apagar_conta(conta_id: int, user_id: str = Depends(exigir_login)):
    con = conectar()
    conta = con.execute("SELECT paga FROM contas WHERE id=? AND user_id=?", (conta_id, user_id)).fetchone()
    if conta is None:
        con.close()
        raise HTTPException(status_code=404, detail="Essa conta não existe.")
    if conta[0] == 1:
        con.close()
        raise HTTPException(status_code=400, detail="Não dá pra apagar uma conta paga. Use 'desfazer' primeiro.")
    # se for fatura, apaga também os itens dela (não deixar itens órfãos)
    con.execute("DELETE FROM fatura_itens WHERE conta_id=? AND user_id=?", (conta_id, user_id))
    con.execute("DELETE FROM contas WHERE id=? AND user_id=?", (conta_id, user_id))
    con.commit()
    con.close()
    return {"status": "conta apagada"}

@app.put("/contas/{conta_id}")
def editar_conta(conta_id: int, item: EditarConta, user_id: str = Depends(exigir_login)):
    con = conectar()
    conta = con.execute("SELECT paga FROM contas WHERE id=? AND user_id=?", (conta_id, user_id)).fetchone()
    if conta is None:
        con.close()
        raise HTTPException(status_code=404, detail="Essa conta não existe.")
    if conta[0] == 1:
        con.close()
        raise HTTPException(status_code=400, detail="Não dá pra editar uma conta paga. Use 'desfazer' primeiro.")
    if not data_valida(item.vencimento):
        con.close()
        raise HTTPException(status_code=400, detail="Vencimento inválido (use AAAA-MM-DD, ano entre 2000 e 2100).")
    con.execute(
        "UPDATE contas SET nome=?, valor_centavos=?, vencimento=?, tipo=? WHERE id=? AND user_id=?",
        (item.nome, item.valor_centavos, item.vencimento, item.tipo, conta_id, user_id)
    )
    con.commit()
    con.close()
    return {"status": "conta editada"}

@app.get("/contas")
def listar_contas(user_id: str = Depends(exigir_login)):
    gerar_recorrentes_do_mes(user_id)
    con = conectar()
    # M1: só as NÃO arquivadas aparecem na tela principal
    linhas = con.execute(
        "SELECT id, nome, valor_centavos, vencimento, tipo, paga, caixinha_paga_id, tipo_conta FROM contas WHERE (arquivada=0 OR arquivada IS NULL) AND user_id=?",
        (user_id,)
    ).fetchall()
    resultado = []
    for l in linhas:
        tipo_conta = l[7] or "simples"
        # fatura: valor exibido é a soma dos itens; simples: o valor guardado
        total = total_conta(con, user_id, l[0], tipo_conta, l[2])
        qtd_itens = 0
        if tipo_conta == "fatura":
            qtd_itens = con.execute(
                "SELECT COUNT(*) FROM fatura_itens WHERE conta_id=? AND user_id=?", (l[0], user_id)
            ).fetchone()[0]
        resultado.append({
            "id": l[0],
            "nome": l[1],
            "valor_reais": total / 100,
            "vencimento": l[3],
            "tipo": l[4],
            "paga": bool(l[5]),
            "caixinha_paga_id": l[6],
            "tipo_conta": tipo_conta,
            "qtd_itens": qtd_itens
        })
    con.close()
    return resultado

@app.post("/contas/{conta_id}/pagar")
def pagar_conta(conta_id: int, item: PagamentoConta, user_id: str = Depends(exigir_login)):
    con = conectar()

    # a conta existe?
    conta = con.execute(
        "SELECT id, valor_centavos, paga, tipo_conta FROM contas WHERE id=? AND user_id=?", (conta_id, user_id)
    ).fetchone()
    if conta is None:
        con.close()
        raise HTTPException(status_code=404, detail="Essa conta não existe.")

    # já foi paga?
    if conta[2] == 1:
        con.close()
        raise HTTPException(status_code=400, detail="Essa conta já foi paga.")

    # valor a pagar: fatura = soma dos itens; simples = valor guardado
    valor = total_conta(con, user_id, conta_id, conta[3] or "simples", conta[1])
    if valor <= 0:
        con.close()
        raise HTTPException(status_code=400, detail="Essa fatura não tem itens para pagar.")

    # a caixinha é do usuário e tem saldo suficiente?
    if con.execute("SELECT id FROM caixinhas WHERE id=? AND user_id=?", (item.caixinha_id, user_id)).fetchone() is None:
        con.close()
        raise HTTPException(status_code=404, detail="Caixinha não encontrada.")
    if saldo_da_caixinha(con, user_id, item.caixinha_id) < valor:
        con.close()
        raise HTTPException(status_code=400, detail="Saldo insuficiente nessa caixinha.")

    # tira o dinheiro da caixinha (pagamento)
    con.execute(
        "INSERT INTO lancamentos (tipo, valor_centavos, descricao, caixinha_id, data, user_id) VALUES (?, ?, ?, ?, ?, ?)",
        ("pagamento", valor, "pagamento de conta", item.caixinha_id, data_hoje(), user_id)
    )
    # marca a conta como paga e guarda de qual caixinha saiu
    con.execute(
        "UPDATE contas SET paga=1, caixinha_paga_id=? WHERE id=? AND user_id=?",
        (item.caixinha_id, conta_id, user_id)
    )
    con.commit()
    con.close()
    return {"status": "conta paga"}

@app.post("/contas/{conta_id}/desfazer-pagamento")
def desfazer_pagamento(conta_id: int, user_id: str = Depends(exigir_login)):
    con = conectar()
    conta = con.execute(
        "SELECT id, valor_centavos, paga, caixinha_paga_id, tipo_conta FROM contas WHERE id=? AND user_id=?", (conta_id, user_id)
    ).fetchone()
    if conta is None:
        con.close()
        raise HTTPException(status_code=404, detail="Essa conta não existe.")
    if conta[2] == 0:
        con.close()
        raise HTTPException(status_code=400, detail="Essa conta não está paga.")

    # o valor pago foi o total da conta (fatura = soma dos itens, que ficam congelados enquanto paga)
    valor = total_conta(con, user_id, conta_id, conta[4] or "simples", conta[1])
    caixinha_id = conta[3]

    # remove o lançamento de pagamento criado (o mais recente dessa caixinha com esse valor)
    lanc = con.execute(
        "SELECT id FROM lancamentos WHERE caixinha_id=? AND valor_centavos=? AND tipo='pagamento' AND descricao='pagamento de conta' AND user_id=? ORDER BY id DESC LIMIT 1",
        (caixinha_id, valor, user_id)
    ).fetchone()
    if lanc is not None:
        con.execute("DELETE FROM lancamentos WHERE id=? AND user_id=?", (lanc[0], user_id))

    # marca a conta como não paga de novo
    con.execute("UPDATE contas SET paga=0, caixinha_paga_id=NULL WHERE id=? AND user_id=?", (conta_id, user_id))
    con.commit()
    con.close()
    return {"status": "pagamento desfeito"}


# ---- M1: arquivar contas (some da tela, mas fica no banco pro histórico) ----

@app.get("/contas/arquivadas")
def listar_contas_arquivadas(user_id: str = Depends(exigir_login)):
    con = conectar()
    linhas = con.execute(
        "SELECT id, nome, valor_centavos, vencimento, tipo, paga, caixinha_paga_id, tipo_conta FROM contas WHERE arquivada=1 AND user_id=? ORDER BY vencimento DESC",
        (user_id,)
    ).fetchall()
    resultado = []
    for l in linhas:
        tipo_conta = l[7] or "simples"
        total = total_conta(con, user_id, l[0], tipo_conta, l[2])
        resultado.append({
            "id": l[0], "nome": l[1], "valor_reais": total / 100,
            "vencimento": l[3], "tipo": l[4], "paga": bool(l[5]),
            "caixinha_paga_id": l[6], "tipo_conta": tipo_conta
        })
    con.close()
    return resultado

@app.post("/contas/{conta_id}/arquivar")
def arquivar_conta(conta_id: int, user_id: str = Depends(exigir_login)):
    con = conectar()
    conta = con.execute("SELECT paga FROM contas WHERE id=? AND user_id=?", (conta_id, user_id)).fetchone()
    if conta is None:
        con.close()
        raise HTTPException(status_code=404, detail="Essa conta não existe.")
    if conta[0] != 1:
        con.close()
        raise HTTPException(status_code=400, detail="Só dá pra arquivar contas já pagas.")
    con.execute("UPDATE contas SET arquivada=1 WHERE id=? AND user_id=?", (conta_id, user_id))
    con.commit()
    con.close()
    return {"status": "conta arquivada"}

@app.post("/contas/{conta_id}/desarquivar")
def desarquivar_conta(conta_id: int, user_id: str = Depends(exigir_login)):
    con = conectar()
    existe = con.execute("SELECT id FROM contas WHERE id=? AND user_id=?", (conta_id, user_id)).fetchone()
    if existe is None:
        con.close()
        raise HTTPException(status_code=404, detail="Essa conta não existe.")
    con.execute("UPDATE contas SET arquivada=0 WHERE id=? AND user_id=?", (conta_id, user_id))
    con.commit()
    con.close()
    return {"status": "conta desarquivada"}

@app.post("/contas/arquivar-antigas")
def arquivar_antigas(user_id: str = Depends(exigir_login)):
    # arquiva de uma vez todas as contas PAGAS cujo vencimento é de um mês anterior ao atual
    con = conectar()
    hoje = date.today()
    inicio_mes = f"{hoje.year:04d}-{hoje.month:02d}-01"
    cur = con.execute(
        "UPDATE contas SET arquivada=1 WHERE paga=1 AND (arquivada=0 OR arquivada IS NULL) AND vencimento < ? AND user_id=?",
        (inicio_mes, user_id)
    )
    qtd = cur.rowcount
    con.commit()
    con.close()
    return {"status": "arquivadas", "quantidade": qtd}


# ---- itens de fatura (D) ----

@app.get("/contas/{conta_id}/itens")
def listar_itens_fatura(conta_id: int, user_id: str = Depends(exigir_login)):
    con = conectar()
    linhas = con.execute(
        "SELECT id, descricao, valor_centavos, data FROM fatura_itens WHERE conta_id=? AND user_id=? ORDER BY id",
        (conta_id, user_id)
    ).fetchall()
    con.close()
    return [
        {"id": l[0], "descricao": l[1], "valor_reais": l[2] / 100, "data": l[3]}
        for l in linhas
    ]

@app.post("/contas/{conta_id}/itens")
def adicionar_item_fatura(conta_id: int, item: NovoItemFatura, user_id: str = Depends(exigir_login)):
    con = conectar()
    conta = con.execute(
        "SELECT tipo_conta, paga FROM contas WHERE id=? AND user_id=?", (conta_id, user_id)
    ).fetchone()
    if conta is None:
        con.close()
        raise HTTPException(status_code=404, detail="Essa conta não existe.")
    if (conta[0] or "simples") != "fatura":
        con.close()
        raise HTTPException(status_code=400, detail="Só dá pra adicionar itens em contas do tipo fatura.")
    if conta[1] == 1:
        con.close()
        raise HTTPException(status_code=400, detail="A fatura já foi paga. Desfaça o pagamento para alterar os itens.")
    if item.valor_centavos <= 0:
        con.close()
        raise HTTPException(status_code=400, detail="O valor do item precisa ser maior que zero.")
    con.execute(
        "INSERT INTO fatura_itens (conta_id, descricao, valor_centavos, data, user_id) VALUES (?, ?, ?, ?, ?)",
        (conta_id, item.descricao, item.valor_centavos, data_hoje(), user_id)
    )
    con.commit()
    con.close()
    return {"status": "item adicionado"}

@app.delete("/contas/{conta_id}/itens/{item_id}")
def apagar_item_fatura(conta_id: int, item_id: int, user_id: str = Depends(exigir_login)):
    con = conectar()
    conta = con.execute("SELECT paga FROM contas WHERE id=? AND user_id=?", (conta_id, user_id)).fetchone()
    if conta is None:
        con.close()
        raise HTTPException(status_code=404, detail="Essa conta não existe.")
    if conta[0] == 1:
        con.close()
        raise HTTPException(status_code=400, detail="A fatura já foi paga. Desfaça o pagamento para alterar os itens.")
    existe = con.execute(
        "SELECT id FROM fatura_itens WHERE id=? AND conta_id=? AND user_id=?", (item_id, conta_id, user_id)
    ).fetchone()
    if existe is None:
        con.close()
        raise HTTPException(status_code=404, detail="Esse item não existe nessa fatura.")
    con.execute("DELETE FROM fatura_itens WHERE id=? AND user_id=?", (item_id, user_id))
    con.commit()
    con.close()
    return {"status": "item apagado"}


# ========================================================
# ROTAS DE RECORRENTES (assinaturas que se repetem todo mês)
# ========================================================

@app.post("/recorrentes")
def criar_recorrente(item: NovaRecorrente, user_id: str = Depends(exigir_login)):
    con = conectar()
    # E2: se veio vínculo de fatura, confere que é uma fatura válida
    if item.conta_fatura_id is not None:
        f = con.execute("SELECT tipo_conta FROM contas WHERE id=? AND user_id=?", (item.conta_fatura_id, user_id)).fetchone()
        if f is None or (f[0] or "simples") != "fatura":
            con.close()
            raise HTTPException(status_code=400, detail="Escolha uma fatura de cartão válida.")
    con.execute(
        "INSERT INTO recorrentes (nome, valor_centavos, dia_vencimento, tipo, conta_fatura_id, user_id) VALUES (?, ?, ?, ?, ?, ?)",
        (item.nome, item.valor_centavos, item.dia_vencimento, item.tipo, item.conta_fatura_id, user_id)
    )
    con.commit()
    con.close()
    return {"status": "recorrente criada"}

@app.get("/recorrentes")
def listar_recorrentes(user_id: str = Depends(exigir_login)):
    con = conectar()
    linhas = con.execute(
        "SELECT id, nome, valor_centavos, dia_vencimento, tipo, conta_fatura_id FROM recorrentes WHERE user_id=?",
        (user_id,)
    ).fetchall()
    con.close()
    return [
        {"id": l[0], "nome": l[1], "valor_reais": l[2] / 100, "dia_vencimento": l[3], "tipo": l[4], "conta_fatura_id": l[5]}
        for l in linhas
    ]

@app.post("/recorrentes/{recorrente_id}/fatura")
def vincular_fatura(recorrente_id: int, item: VincularFatura, user_id: str = Depends(exigir_login)):
    con = conectar()
    rec = con.execute("SELECT id, nome FROM recorrentes WHERE id=? AND user_id=?", (recorrente_id, user_id)).fetchone()
    if rec is None:
        con.close()
        raise HTTPException(status_code=404, detail="Essa assinatura não existe.")
    if item.conta_fatura_id is not None:
        f = con.execute("SELECT tipo_conta FROM contas WHERE id=? AND user_id=?", (item.conta_fatura_id, user_id)).fetchone()
        if f is None or (f[0] or "simples") != "fatura":
            con.close()
            raise HTTPException(status_code=400, detail="Escolha uma fatura de cartão válida.")
        # ao vincular, remove a conta avulsa NÃO PAGA deste mês com o mesmo nome
        # (evita cobrar duas vezes: uma avulsa + uma dentro da fatura)
        hoje = date.today()
        mes_str = f"{hoje.year:04d}-{hoje.month:02d}"
        con.execute(
            "DELETE FROM contas WHERE nome=? AND paga=0 AND (tipo_conta='simples' OR tipo_conta IS NULL) AND vencimento LIKE ? AND user_id=?",
            (rec[1], mes_str + "%", user_id)
        )
    con.execute("UPDATE recorrentes SET conta_fatura_id=? WHERE id=? AND user_id=?", (item.conta_fatura_id, recorrente_id, user_id))
    con.commit()
    con.close()
    return {"status": "vínculo atualizado"}

@app.delete("/recorrentes/{recorrente_id}")
def apagar_recorrente(recorrente_id: int, user_id: str = Depends(exigir_login)):
    con = conectar()
    existe = con.execute("SELECT id FROM recorrentes WHERE id=? AND user_id=?", (recorrente_id, user_id)).fetchone()
    if existe is None:
        con.close()
        raise HTTPException(status_code=404, detail="Essa assinatura não existe.")
    # apaga só o molde; as contas já geradas continuam existindo
    con.execute("DELETE FROM recorrentes WHERE id=? AND user_id=?", (recorrente_id, user_id))
    con.commit()
    con.close()
    return {"status": "assinatura apagada"}


# ========================================================
# ROTAS DE BANCOS
# ========================================================

@app.post("/bancos")
def criar_banco(item: NovoBanco, user_id: str = Depends(exigir_login)):
    con = conectar()
    con.execute("INSERT INTO bancos (nome, user_id) VALUES (?, ?)", (item.nome, user_id))
    con.commit()
    con.close()
    return {"status": "banco criado"}

@app.get("/bancos")
def listar_bancos(user_id: str = Depends(exigir_login)):
    con = conectar()
    linhas = con.execute("SELECT id, nome FROM bancos WHERE user_id=?", (user_id,)).fetchall()
    con.close()
    return [{"id": l[0], "nome": l[1]} for l in linhas]

@app.delete("/bancos/{banco_id}")
def apagar_banco(banco_id: int, user_id: str = Depends(exigir_login)):
    con = conectar()
    existe = con.execute("SELECT id FROM bancos WHERE id=? AND user_id=?", (banco_id, user_id)).fetchone()
    if existe is None:
        con.close()
        raise HTTPException(status_code=404, detail="Esse banco não existe.")
    # tem caixinhas dentro dele?
    qtd = con.execute("SELECT COUNT(*) FROM caixinhas WHERE banco_id=? AND user_id=?", (banco_id, user_id)).fetchone()[0]
    if qtd > 0:
        con.close()
        raise HTTPException(
            status_code=400,
            detail="Esse banco tem caixinhas. Mova ou apague as caixinhas antes."
        )
    con.execute("DELETE FROM bancos WHERE id=? AND user_id=?", (banco_id, user_id))
    con.commit()
    con.close()
    return {"status": "banco apagado"}


# ========================================================
# ROTAS DE CATEGORIAS (rótulos das contas/assinaturas)
# ========================================================

@app.get("/categorias")
def listar_categorias(user_id: str = Depends(exigir_login)):
    con = conectar()
    linhas = con.execute("SELECT id, nome FROM categorias WHERE user_id=? ORDER BY id", (user_id,)).fetchall()
    con.close()
    return [{"id": l[0], "nome": l[1]} for l in linhas]

@app.post("/categorias")
def criar_categoria(item: NovaCategoria, user_id: str = Depends(exigir_login)):
    nome = item.nome.strip()
    if not nome:
        raise HTTPException(status_code=400, detail="Dê um nome à categoria.")
    con = conectar()
    # evita duplicar (ignorando maiúsculas/minúsculas)
    ja_existe = con.execute("SELECT id FROM categorias WHERE user_id=? AND lower(nome)=lower(?)", (user_id, nome)).fetchone()
    if ja_existe is not None:
        con.close()
        raise HTTPException(status_code=400, detail="Já existe uma categoria com esse nome.")
    con.execute("INSERT INTO categorias (nome, user_id) VALUES (?, ?)", (nome, user_id))
    con.commit()
    con.close()
    return {"status": "categoria criada"}

@app.delete("/categorias/{categoria_id}")
def apagar_categoria(categoria_id: int, user_id: str = Depends(exigir_login)):
    con = conectar()
    existe = con.execute("SELECT id FROM categorias WHERE id=? AND user_id=?", (categoria_id, user_id)).fetchone()
    if existe is None:
        con.close()
        raise HTTPException(status_code=404, detail="Essa categoria não existe.")
    # remoção permitida mesmo em uso — contas antigas mantêm o rótulo (o campo é só texto)
    con.execute("DELETE FROM categorias WHERE id=? AND user_id=?", (categoria_id, user_id))
    con.commit()
    con.close()
    return {"status": "categoria apagada"}


# ========================================================
# ROTAS DE REGRAS DE SALÁRIO (E4)
# ========================================================

@app.get("/regras")
def listar_regras(user_id: str = Depends(exigir_login)):
    con = conectar()
    linhas = con.execute(
        "SELECT id, gatilho, modo, valor, caixinha_id FROM regras_salario WHERE user_id=? ORDER BY id",
        (user_id,)
    ).fetchall()
    con.close()
    return [
        {"id": l[0], "gatilho": l[1], "modo": l[2], "valor": l[3], "caixinha_id": l[4]}
        for l in linhas
    ]

@app.post("/regras")
def criar_regra(item: NovaRegra, user_id: str = Depends(exigir_login)):
    gatilho = item.gatilho.strip()
    if not gatilho:
        raise HTTPException(status_code=400, detail="Informe o nome do gatilho (ex.: Salário).")
    if item.modo not in ("percentual", "fixo"):
        raise HTTPException(status_code=400, detail="Modo inválido.")
    if item.valor <= 0:
        raise HTTPException(status_code=400, detail="O valor precisa ser maior que zero.")
    if item.modo == "percentual" and item.valor > 100:
        raise HTTPException(status_code=400, detail="A porcentagem não pode passar de 100%.")
    con = conectar()
    existe = con.execute("SELECT id FROM caixinhas WHERE id=? AND user_id=?", (item.caixinha_id, user_id)).fetchone()
    if existe is None:
        con.close()
        raise HTTPException(status_code=400, detail="Essa caixinha não existe.")
    con.execute(
        "INSERT INTO regras_salario (gatilho, modo, valor, caixinha_id, user_id) VALUES (?, ?, ?, ?, ?)",
        (gatilho, item.modo, item.valor, item.caixinha_id, user_id)
    )
    con.commit()
    con.close()
    return {"status": "regra criada"}

@app.delete("/regras/{regra_id}")
def apagar_regra(regra_id: int, user_id: str = Depends(exigir_login)):
    con = conectar()
    existe = con.execute("SELECT id FROM regras_salario WHERE id=? AND user_id=?", (regra_id, user_id)).fetchone()
    if existe is None:
        con.close()
        raise HTTPException(status_code=404, detail="Essa regra não existe.")
    con.execute("DELETE FROM regras_salario WHERE id=? AND user_id=?", (regra_id, user_id))
    con.commit()
    con.close()
    return {"status": "regra apagada"}


# ========================================================
# ROTAS DA RETROSPECTIVA MENSAL (E6) — guarda só qual mês já foi mostrado;
# o resumo é calculado no front a partir dos lançamentos.
# ========================================================

@app.get("/wrapped-status")
def wrapped_status(user_id: str = Depends(exigir_login)):
    con = conectar()
    r = con.execute("SELECT valor FROM config WHERE user_id=? AND chave='wrapped_visto_ate'", (user_id,)).fetchone()
    con.close()
    return {"visto_ate": r[0] if r else None}

@app.post("/wrapped-visto")
def wrapped_visto(item: WrappedVisto, user_id: str = Depends(exigir_login)):
    con = conectar()
    _upsert_config(con, user_id, "wrapped_visto_ate", item.mes)
    con.commit()
    con.close()
    return {"status": "ok"}


# ========================================================
# ROTAS DO LEITOR DE EXTRATO (E3)
# ========================================================

@app.post("/importar/analisar")
def importar_analisar(item: ImportarAnalise, user_id: str = Depends(exigir_login)):
    con = conectar()
    caixinhas = [(c[0], (c[1] or "").lower()) for c in con.execute("SELECT id, nome FROM caixinhas WHERE user_id=?", (user_id,)).fetchall()]
    con.close()
    if item.tipo_arquivo == "ofx":
        linhas = parse_ofx(item.conteudo, caixinhas)
    else:
        linhas = parse_csv(item.conteudo, caixinhas)
    return {"linhas": linhas, "total": len(linhas)}

@app.post("/importar/conta-imagem")
def importar_conta_imagem(item: ImportarContaImagem, user_id: str = Depends(exigir_login)):
    """Lê uma foto/print ou PDF de conta e devolve uma prévia (nome, valor, vencimento)
    pra o usuário conferir/corrigir antes de criar a conta de verdade via POST /contas."""
    if not OCR_DISPONIVEL:
        raise HTTPException(
            status_code=500,
            detail="Leitor de conta por imagem não está instalado neste servidor. "
                    "Rode: pip install pytesseract Pillow PyMuPDF, e instale o Tesseract "
                    "(ver estudo_ocr_conta_imagem.md)."
        )
    conteudo = item.conteudo
    if "," in conteudo and conteudo.strip().startswith("data:"):
        conteudo = conteudo.split(",", 1)[1]  # tira o prefixo "data:...;base64,"
    try:
        dados = base64.b64decode(conteudo)
    except Exception:
        raise HTTPException(status_code=400, detail="Arquivo inválido (falha ao decodificar).")
    if len(dados) > TAMANHO_MAX_ARQUIVO_OCR:
        raise HTTPException(status_code=400, detail="Arquivo grande demais (máximo 15 MB).")
    if not dados:
        raise HTTPException(status_code=400, detail="Arquivo vazio.")

    try:
        if item.tipo_arquivo == "pdf":
            texto = ocr_texto_pdf(dados)
        else:
            texto = ocr_texto_imagem(dados)
    except pytesseract.TesseractNotFoundError:
        raise HTTPException(
            status_code=500,
            detail="Tesseract não encontrado no caminho configurado. Verifique a instalação "
                    "(ver estudo_ocr_conta_imagem.md) ou defina a variável de ambiente TESSERACT_CMD."
        )
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Não consegui ler o arquivo: {e}")

    if not texto.strip():
        raise HTTPException(status_code=400, detail="Não consegui ler nenhum texto nesse arquivo. Tente uma foto mais nítida.")

    return extrair_conta(texto)

@app.post("/importar/confirmar")
def importar_confirmar(item: ImportarConfirmar, user_id: str = Depends(exigir_login)):
    con = conectar()
    n = 0
    for l in item.linhas:
        if l.valor_centavos <= 0:
            continue
        data = l.data if re.match(r"^\d{4}-\d{2}-\d{2}$", l.data or "") else data_hoje()
        # só usa a caixinha se ela for do próprio usuário (senão vira saída livre)
        cx_ok = l.caixinha_id and con.execute(
            "SELECT id FROM caixinhas WHERE id=? AND user_id=?", (l.caixinha_id, user_id)
        ).fetchone() is not None
        if l.tipo == "entrada":
            # entrada importada NÃO dispara regras de salário (é histórico); vai pro saldo livre
            con.execute(
                "INSERT INTO lancamentos (tipo, valor_centavos, descricao, caixinha_id, data, user_id) VALUES ('entrada', ?, ?, NULL, ?, ?)",
                (l.valor_centavos, l.descricao, data, user_id)
            )
        elif cx_ok:
            con.execute(
                "INSERT INTO lancamentos (tipo, valor_centavos, descricao, caixinha_id, data, user_id) VALUES ('pagamento', ?, ?, ?, ?, ?)",
                (l.valor_centavos, l.descricao, l.caixinha_id, data, user_id)
            )
        else:
            con.execute(
                "INSERT INTO lancamentos (tipo, valor_centavos, descricao, caixinha_id, data, user_id) VALUES ('saida_livre', ?, ?, NULL, ?, ?)",
                (l.valor_centavos, l.descricao, data, user_id)
            )
        n += 1
    con.commit()
    con.close()
    return {"status": "importado", "quantidade": n}
