"""
Migra os dados do SQLite (financeiro.db) para o Postgres do Supabase, JÁ carimbando
tudo com o SEU user_id (multi-usuário).

- Lê a conexão do .env (PGHOST/PGPORT/PGDATABASE/PGUSER/PGPASSWORD/PGSSLMODE) — nunca
  escreve a senha no código nem imprime ela.
- NÃO altera o financeiro.db (abre só-leitura).
- Cria o schema no Postgres (idempotente), LIMPA as tabelas de destino e copia tudo,
  colocando user_id = SEU UUID em cada linha; no fim acerta as sequences (IDENTITY).
- A linha antiga 'senha_hash' da config é descartada (agora o login é Supabase Auth).

Uso:
    python migrar_para_supabase.py <SEU_UUID> [caminho_do_financeiro.db]
    (o UUID também pode vir da variável de ambiente OWNER_USER_ID)
    (o caminho padrão é financeiro.db ao lado deste script)
"""
import os, sys, sqlite3
import psycopg2
from psycopg2.extras import execute_values

AQUI = os.path.dirname(os.path.abspath(__file__))

def carregar_env():
    cfg = {}
    caminho = os.path.join(AQUI, ".env")
    if not os.path.exists(caminho):
        sys.exit("ERRO: .env não encontrado ao lado do script (com PGHOST/PGUSER/PGPASSWORD...).")
    for linha in open(caminho, encoding="utf-8"):
        linha = linha.rstrip("\n")
        if not linha or linha.lstrip().startswith("#") or "=" not in linha:
            continue
        k, v = linha.split("=", 1)
        cfg[k.strip()] = v.strip().strip("'").strip('"')
    return cfg

# DDL do Postgres — MESMO schema do main.py (com user_id em tudo e config por usuário).
DDL = [
    "CREATE TABLE IF NOT EXISTS bancos (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome TEXT, user_id UUID)",
    "CREATE TABLE IF NOT EXISTS caixinhas (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome TEXT, banco_id BIGINT, meta_centavos BIGINT DEFAULT 0, meta_prazo TEXT, user_id UUID)",
    "CREATE TABLE IF NOT EXISTS lancamentos (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tipo TEXT, valor_centavos BIGINT, descricao TEXT, caixinha_id BIGINT, data TEXT, user_id UUID)",
    "CREATE TABLE IF NOT EXISTS contas (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome TEXT, valor_centavos BIGINT, vencimento TEXT, tipo TEXT, paga INTEGER DEFAULT 0, caixinha_paga_id BIGINT, tipo_conta TEXT DEFAULT 'simples', arquivada INTEGER DEFAULT 0, user_id UUID)",
    "CREATE TABLE IF NOT EXISTS recorrentes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome TEXT, valor_centavos BIGINT, dia_vencimento INTEGER, tipo TEXT, conta_fatura_id BIGINT, user_id UUID)",
    "CREATE TABLE IF NOT EXISTS config (user_id UUID, chave TEXT, valor TEXT, PRIMARY KEY (user_id, chave))",
    "CREATE TABLE IF NOT EXISTS fatura_itens (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, conta_id BIGINT, descricao TEXT, valor_centavos BIGINT, data TEXT, user_id UUID)",
    "CREATE TABLE IF NOT EXISTS categorias (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome TEXT, user_id UUID)",
    "CREATE TABLE IF NOT EXISTS regras_salario (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, gatilho TEXT, modo TEXT, valor BIGINT, caixinha_id BIGINT, user_id UUID)",
]
# tabelas com coluna id (IDENTITY) — config é tratada à parte (PK composta, sem id)
TABELAS_ID = ["bancos", "caixinhas", "lancamentos", "contas", "recorrentes",
              "fatura_itens", "categorias", "regras_salario"]

def colunas_sqlite(scon, tabela):
    return [r[1] for r in scon.execute(f"PRAGMA table_info({tabela})").fetchall()]

def colunas_pg(pcur, tabela):
    pcur.execute(
        "SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=%s",
        (tabela,))
    return {r[0] for r in pcur.fetchall()}

def main():
    owner = (sys.argv[1] if len(sys.argv) > 1 else os.environ.get("OWNER_USER_ID", "")).strip()
    if not owner or owner.upper().startswith("SEU_UUID"):
        sys.exit("ERRO: informe o SEU UUID (do usuário no Supabase Auth):\n"
                 "  python migrar_para_supabase.py <SEU_UUID> [financeiro.db]")
    sqlite_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(AQUI, "financeiro.db")
    if not os.path.exists(sqlite_path):
        sys.exit(f"ERRO: SQLite não encontrado: {sqlite_path}")
    cfg = carregar_env()

    scon = sqlite3.connect(f"file:{sqlite_path}?mode=ro", uri=True)  # SÓ-LEITURA
    tabelas_origem = {r[0] for r in scon.execute(
        "SELECT name FROM sqlite_master WHERE type='table'").fetchall()}

    pcon = psycopg2.connect(
        host=cfg["PGHOST"], port=cfg["PGPORT"], dbname=cfg["PGDATABASE"],
        user=cfg["PGUSER"], password=cfg["PGPASSWORD"],
        sslmode=cfg.get("PGSSLMODE", "require"), connect_timeout=20)
    pcur = pcon.cursor()

    print(f"Origem : {sqlite_path}")
    print(f"Destino: {cfg['PGHOST']} / {cfg['PGDATABASE']} (Supabase)")
    print(f"user_id: {owner}\n")

    for ddl in DDL:
        pcur.execute(ddl)
    pcur.execute("TRUNCATE TABLE " + ", ".join(TABELAS_ID + ["config"]) + " RESTART IDENTITY")
    pcon.commit()

    resumo = []
    for t in TABELAS_ID:
        if t not in tabelas_origem:
            resumo.append((t, 0, 0, "(nao existe na origem)")); continue
        dst = colunas_pg(pcur, t)
        cols = [c for c in colunas_sqlite(scon, t) if c in dst and c != "user_id"]
        rows = scon.execute(f"SELECT {', '.join(cols)} FROM {t}").fetchall()
        n_src = len(rows)
        cols_ins = cols + ["user_id"]
        vals = [tuple(r) + (owner,) for r in rows]
        if vals:
            execute_values(pcur, f"INSERT INTO {t} ({', '.join(cols_ins)}) VALUES %s", vals)
        pcon.commit()
        pcur.execute(f"SELECT COUNT(*) FROM {t}"); n_dst = pcur.fetchone()[0]
        pcur.execute("SELECT setval(pg_get_serial_sequence(%s,'id'), "
                     "COALESCE((SELECT MAX(id) FROM " + t + "),1), (SELECT COUNT(*) FROM " + t + ")>0)", (t,))
        pcon.commit()
        resumo.append((t, n_src, n_dst, "OK" if n_src == n_dst else "DIVERGENCIA!"))

    # config: descarta senha_hash (obsoleto); carimba user_id
    n_src = n_dst = 0
    if "config" in tabelas_origem:
        linhas = scon.execute("SELECT chave, valor FROM config WHERE chave <> 'senha_hash'").fetchall()
        n_src = len(linhas)
        vals = [(owner, chave, valor) for (chave, valor) in linhas]
        if vals:
            execute_values(pcur, "INSERT INTO config (user_id, chave, valor) VALUES %s", vals)
        pcon.commit()
        pcur.execute("SELECT COUNT(*) FROM config"); n_dst = pcur.fetchone()[0]
    resumo.append(("config", n_src, n_dst, "OK" if n_src == n_dst else "DIVERGENCIA!"))

    scon.close(); pcon.close()

    print(f"{'tabela':<16}{'origem':>8}{'destino':>9}   status")
    print("-" * 46)
    ok = True
    for t, a, b, s in resumo:
        print(f"{t:<16}{a:>8}{b:>9}   {s}")
        if s.startswith("DIVERG"): ok = False
    print("\n" + ("MIGRACAO OK — seus dados estao no Supabase com o seu user_id." if ok else "ATENCAO: houve divergencia."))

if __name__ == "__main__":
    main()
